services:
  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
